# Generated by Django 3.2.4 on 2021-08-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210804_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchitem',
            name='active',
        ),
    ]
