# Generated by Django 3.2.4 on 2021-08-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_watchitem_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchItem',
            new_name='Watchlist',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='watcher',
            new_name='user',
        ),
    ]
